# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: canary-monitoring-only
# spec:
#   args:
#   - name: stable-service
#   - name: canary-service
#   metrics:
#   # Metric 1: Stable Success Rate
#   - name: stable-success-rate
#     interval: 30s # How often to query Prometheus
#     provider:
#       prometheus:
#         address: http://prometheus-server.monitoring.svc.cluster.local:9090 # Replace with your Prometheus address
#         query: |
#           sum(rate(istio_requests_total{destination_service=~"{{args.stable-service}}.*", response_code!~"5.*"}[1m]))
#           /
#           sum(rate(istio_requests_total{destination_service=~"{{args.stable-service}}.*"}[1m]))
  
#   # Metric 2: Canary Success Rate
#   - name: canary-success-rate
#     interval: 30s
#     provider:
#       prometheus:
#         address: http://prometheus-server.monitoring.svc.cluster.local:9090
#         query: |
#           sum(rate(istio_requests_total{destination_service=~"{{args.canary-service}}.*", response_code!~"5.*"}[1m]))
#           /
#           sum(rate(istio_requests_total{destination_service=~"{{args.canary-service}}.*"}[1m]))

#   # # Metric 3: Comparison (This still runs but its result is ignored by dry-run)
#   # - name: comparison-check
#   #   interval: 30s
#   #   successCondition: 1 == 1 # A condition that is always true



# apiVersion: argoproj.io/v1alpha1
# kind: AnalysisTemplate
# metadata:
#   name: canary-monitoring-only
# spec:
#   args:
#   - name: stable-service
#   - name: canary-service
#   metrics:
#   # Metric 1: Stable Success Rate
#   - name: stable-success-rate
#     interval: 60s
#     count: 5
#     successCondition: result > 0  
#     # 🔥 jsonPath REMOVED
#     provider:
#       prometheus:
#         address: http://prometheus.istio-system.svc.cluster.local:9090
#         # 🔥 PromQL updated to use 'max()' to guarantee a single scalar result
#         query: |
#           max(
#             sum(rate(istio_requests_total{destination_service=~"{{args.stable-service}}.*", response_code!~"5.*"}[1m]))
#             /
#             sum(rate(istio_requests_total{destination_service=~"{{args.stable-service}}.*"}[1m]))
#           )
  
#   # Metric 2: Canary Success Rate
#   - name: canary-success-rate
#     interval: 60s
#     count: 5
#     successCondition: result > 0
#     # 🔥 jsonPath REMOVED
#     provider:
#       prometheus:
#         address: http://prometheus.istio-system.svc.cluster.local:9090
#         # 🔥 PromQL updated to use 'max()' to guarantee a single scalar result
#         query: |
#           max(
#             sum(rate(istio_requests_total{destination_service=~"{{args.canary-service}}.*", response_code!~"5.*"}[1m]))
#             /
#             sum(rate(istio_requests_total{destination_service=~"{{args.canary-service}}.*"}[1m]))
#           )


apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
spec:
  args:
  - name: stable-service
  - name: canary-service
  metrics:
  - name: relative-error-rate
    successCondition: len(result) == 0 || result[0] <= 0 # Pass if (Canary - 1.5*Stable) is negative or zero
    interval: 2m
    failureLimit: 1 
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090 
        query: |
         # # Calculate Canary Error Rate (0 to 1)
          # (
          #   sum(rate(istio_requests_total{destination_service_name="{{args.canary-service}}", response_code=~"5[0-9]{2}"}[2m])) 
          #   / 
          #   (sum(rate(istio_requests_total{destination_service_name="{{args.canary-service}}"}[2m]))>0)
          # )
          # - 
          # # Subtract (Stable Error Rate * 1.5)
          # (
          #   1.5 * (
          #     sum(rate(istio_requests_total{destination_service_name="{{args.stable-service}}", response_code=~"5[0-9]{2}"}[2m])) 
          #     / 
          #     (sum(rate(istio_requests_total{destination_service_name="{{args.stable-service}}"}[2m]))>0)
          #   )
          # )
          # sum(rate(istio_requests_total{destination_service_name="{{args.canary-service}}", response_code=~"5[0-9]{2}"}[2m]))*0
          vector(-0.5)
