apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
spec:
  args:
  - name: stable-service
  - name: canary-service
  metrics:
  - name: relative-error-rate
    successCondition: len(result) == 0 || result[0] <= 0 # Pass if (Canary - 1.5*Stable) is negative or zero
    interval: 1m
    failureLimit: 1 
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090 
        query: |
          (
            sum(rate(istio_requests_total{destination_service_name="{{args.canary-service}}", response_code=~"5[0-9]{2}"}[2m])) 
            / 
            (sum(rate(istio_requests_total{destination_service_name="{{args.canary-service}}"}[2m]))>0)
          )
          - 
          # Subtract (Stable Error Rate * 1.5)
          (
            1.5 * (
              sum(rate(istio_requests_total{destination_service_name="{{args.stable-service}}", response_code=~"5[0-9]{2}"}[2m])) 
              / 
              (sum(rate(istio_requests_total{destination_service_name="{{args.stable-service}}"}[2m]))>0)
            )
          )
