apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate-check
spec:
  args:
  - name: stable-service
  - name: canary-service
  metrics:
  - name: relative-error-rate
    successCondition: len(result) == 0 || result[0] <= 0 # Pass if (Canary - 1.5*Stable) is negative or zero
    interval: 1m
    failureLimit: 1 
    provider:
      prometheus:
        address: http://prometheus.istio-system.svc.cluster.local:9090 
        query: |
          (sum(rate(istio_requests_total{destination_service_name=~"myservice-canary", response_code=~"[45][0-9]{2}"}[10m]))
          /
          sum(rate(istio_requests_total{destination_service_name=~"myservice-canary"}[10m])))
          -1.5*(sum(rate(istio_requests_total{destination_service_name=~"myservice-stable", response_code=~"[45][0-9]{2}"}[10m]))
          /
          sum(rate(istio_requests_total{destination_service_name=~"myservice-stable"}[10m])))
